# Generated by Django 5.0.7 on 2025-01-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Furnaces',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.URLField(max_length=2000)),
                ('name', models.CharField(max_length=1000)),
                ('feature', models.CharField(max_length=1000)),
                ('specification', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.URLField(max_length=2000)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('q_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataRetrivalAPI.customer')),
                ('q_furnace_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataRetrivalAPI.furnaces')),
                ('q_service_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataRetrivalAPI.services')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='query_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataRetrivalAPI.query'),
        ),
    ]
