# Generated by Django 5.0.7 on 2025-06-08 06:39

import DataRetrivalAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnaces',
            name='image',
            field=models.FileField(upload_to=DataRetrivalAPI.models.furnaces_upload_path),
        ),
    ]
