# Generated by Django 5.0.7 on 2025-06-13 14:05

import DataRetrivalAPI.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0002_alter_furnaces_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnaces',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.CreateModel(
            name='FurnaceImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to=DataRetrivalAPI.models.additional_furnace_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='DataRetrivalAPI.furnaces')),
            ],
        ),
    ]
