# Generated by Django 5.0.7 on 2025-07-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0003_rename_image_furnaces_cover_image_furnaceimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='q_customer_id',
        ),
        migrations.RemoveField(
            model_name='query',
            name='q_furnace_id',
        ),
        migrations.RemoveField(
            model_name='query',
            name='q_service_id',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
