# Generated by Django 5.0.7 on 2025-07-12 06:56

import DataRetrivalAPI.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0004_remove_query_q_customer_id_remove_query_q_furnace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.AddField(
            model_name='services',
            name='cover_image',
            field=models.FileField(default='Provide a one-off default now', upload_to=DataRetrivalAPI.models.services_upload_path),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to=DataRetrivalAPI.models.additional_service_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='DataRetrivalAPI.services')),
            ],
        ),
    ]
