# Generated by Django 5.0.7 on 2025-07-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0005_remove_services_image_services_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimages',
            old_name='product',
            new_name='service',
        ),
    ]
