# Generated by Django 5.0.7 on 2025-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0006_rename_product_serviceimages_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnaces',
            name='specification',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
