# Generated by Django 4.2.27 on 2026-01-07 07:36

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0007_alter_furnaces_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnaces',
            name='feature',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='furnaces',
            name='specification',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.TextField(),
        ),
    ]
