# Generated by Django 4.2.27 on 2026-01-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0008_alter_furnaces_feature_alter_furnaces_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnaces',
            name='feature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='furnaces',
            name='specification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(),
        ),
    ]
