# Generated by Django 4.2.27 on 2026-05-05 12:51

import DataRetrivalAPI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRetrivalAPI', '0009_alter_furnaces_feature_alter_furnaces_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cover_image', models.FileField(upload_to=DataRetrivalAPI.models.spare_parts_upload_path)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SparePartImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to=DataRetrivalAPI.models.additional_spare_part_image_path)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='DataRetrivalAPI.spareparts')),
            ],
        ),
    ]
